In [27]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

In [28]:
file_path = "D:\My Statistics\Pandas\Datasets\Kaggle Training Datasets\Airbnb Data\Airbnb_Open_Data.csv"

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\ASUS\AppData\Local\Temp\ipykernel_11028\2264134875.py:1: SyntaxWarning: invalid escape sequence '\M'
  file_path = "D:\My Statistics\Pandas\Datasets\Kaggle Training Datasets\Airbnb Data\Airbnb_Open_Data.csv"

In [29]:
main_data = pd.read_csv(file_path)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11028\2628311240.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  main_data = pd.read_csv(file_path)

In [30]:
main_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [31]:
data = main_data.copy()

In [32]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [34]:
null_value = data.isna().sum()

In [35]:
len(data)

102599

In [36]:
missing_percent = null_value/len(data) * 100

missing_percent

id                                 0.000000
NAME                               0.243667
host id                            0.000000
host_identity_verified             0.281679
host name                          0.395715
neighbourhood group                0.028265
neighbourhood                      0.015595
lat                                0.007797
long                               0.007797
country                            0.518524
country code                       0.127682
instant_bookable                   0.102340
cancellation_policy                0.074075
room type                          0.000000
Construction year                  0.208579
price                              0.240743
service fee                        0.266084
minimum nights                     0.398639
number of reviews                  0.178364
last review                       15.490404
reviews per month                 15.476759
review rate number                 0.317742
calculated host listings count     0.310919
availability 365                   0.436651
house_rules                       50.810437
license                           99.998051
dtype: float64

In [37]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [38]:
columns_to_keep = ['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']

In [39]:
columns_to_drop = ['reviews per month','review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license']

### Filter Method

In [40]:
filter_data = data[columns_to_keep]

### Renaming The Column

In [41]:
filter_data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [42]:
new_column_names = []

for i in filter_data.columns:
    new_column_names.append(i.capitalize())

In [43]:
filter_data.columns = new_column_names

In [44]:
filter_data.duplicated().sum()

np.int64(541)

In [45]:
filter_data.drop_duplicates(inplace= True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11028\551916780.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filter_data.drop_duplicates(inplace= True)

In [46]:
missing_data = filter_data.isna().sum()

In [47]:
missing_data/ len(filter_data) * 100

Id                         0.000000
Name                       0.244959
Host id                    0.000000
Host_identity_verified     0.283172
Host name                  0.395853
Neighbourhood group        0.028415
Neighbourhood              0.015677
Lat                        0.007839
Long                       0.007839
Country                    0.521272
Country code               0.128358
Instant_bookable           0.102883
Cancellation_policy        0.074467
Room type                  0.000000
Construction year          0.209685
Price                      0.242019
Service fee                0.267495
Minimum nights             0.391934
Number of reviews          0.179310
Last review               15.512748
dtype: float64

In [48]:
filter_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 102058 entries, 0 to 102057
Data columns (total 20 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      102058 non-null  int64
 1   Name                    101808 non-null  object
 2   Host id                 102058 non-null  int64
 3   Host_identity_verified  101769 non-null  object
 4   Host name               101654 non-null  object
 5   Neighbourhood group     102029 non-null  object
 6   Neighbourhood           102042 non-null  object
 7   Lat                     102050 non-null  float64
 8   Long                    102050 non-null  float64
 9   Country                 101526 non-null  object
 10  Country code            101927 non-null  object
 11  Instant_bookable        101953 non-null  object
 12  Cancellation_policy     101982 non-null  object
 13  Room type               102058 non-null  object
 14  Construction year       101844 non-null  float64
 15  Price                   101811 non-null  object
 16  Service fee             101785 non-null  object
 17  Minimum nights          101658 non-null  float64
 18  Number of reviews       101875 non-null  float64
 19  Last review             86226 non-null   object
dtypes: float64(5), int64(2), object(13)
memory usage: 16.4+ MB

In [49]:
remove_null_data = filter_data.dropna()

In [50]:
remove_null_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 83969 entries, 0 to 102040
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      83969 non-null  int64
 1   Name                    83969 non-null  object
 2   Host id                 83969 non-null  int64
 3   Host_identity_verified  83969 non-null  object
 4   Host name               83969 non-null  object
 5   Neighbourhood group     83969 non-null  object
 6   Neighbourhood           83969 non-null  object
 7   Lat                     83969 non-null  float64
 8   Long                    83969 non-null  float64
 9   Country                 83969 non-null  object
 10  Country code            83969 non-null  object
 11  Instant_bookable        83969 non-null  object
 12  Cancellation_policy     83969 non-null  object
 13  Room type               83969 non-null  object
 14  Construction year       83969 non-null  float64
 15  Price                   83969 non-null  object
 16  Service fee             83969 non-null  object
 17  Minimum nights          83969 non-null  float64
 18  Number of reviews       83969 non-null  float64
 19  Last review             83969 non-null  object
dtypes: float64(5), int64(2), object(13)
memory usage: 13.5+ MB

In [51]:
remove_null_data['Host_identity_verified'] = remove_null_data['Host_identity_verified'].str.strip().str.capitalize()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11028\1178681990.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remove_null_data['Host_identity_verified'] = remove_null_data['Host_identity_verified'].str.strip().str.capitalize()

In [52]:
remove_null_data.head()

,Id,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Last review
0,1001254,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,1002102,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019
7,1005202,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017

In [53]:
remove_null_data['Neighbourhood'].head(20)

0             Kensington
1                Midtown
4            East Harlem
5            Murray Hill
7     Bedford-Stuyvesant
8         Hell's Kitchen
9        Upper West Side
10             Chinatown
11       Upper West Side
13           South Slope
14       Upper West Side
35    Bedford-Stuyvesant
36           South Slope
38              Bushwick
41          East Village
42           South Slope
44       Upper West Side
45                Harlem
56          Williamsburg
65          Clinton Hill
Name: Neighbourhood, dtype: object

In [54]:
remove_null_data['Cancellation_policy'].str.strip().str.capitalize()

0           Strict
1         Moderate
4         Moderate
5         Flexible
7         Moderate
            ...
102029    Flexible
102030    Moderate
102031    Flexible
102032    Moderate
102040      Strict
Name: Cancellation_policy, Length: 83969, dtype: object

In [55]:
remove_null_data['Cancellation_policy'] = remove_null_data.loc[:,'Cancellation_policy'].str.strip().str.capitalize()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11028\2373800114.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remove_null_data['Cancellation_policy'] = remove_null_data.loc[:,'Cancellation_policy'].str.strip().str.capitalize()

In [56]:
remove_null_data.head()

,Id,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Last review
0,1001254,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,Strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
1,1002102,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,Moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,Moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,Flexible,Entire home/apt,2013.0,$577,$115,3.0,74.0,6/22/2019
7,1005202,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,Moderate,Private room,2009.0,"$1,060",$212,45.0,49.0,10/5/2017

In [57]:
remove_null_data['Price'] = remove_null_data['Price'].str.replace('$','')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11028\605598974.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remove_null_data['Price'] = remove_null_data['Price'].str.replace('$','')

In [58]:
remove_null_data['Service fee'] = remove_null_data.loc[:,'Service fee'].str.replace('$', '')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11028\2993512123.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remove_null_data['Service fee'] = remove_null_data.loc[:,'Service fee'].str.replace('$', '')

In [59]:
remove_null_data.loc[:,'Country code'] = remove_null_data.loc[:,'Country code'].str.strip()

In [60]:
final_stage_data = remove_null_data.copy()

In [61]:
final_stage_data.head()

,Id,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Last review
0,1001254,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,Strict,Private room,2020.0,966,193,10.0,9.0,10/19/2021
1,1002102,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,Moderate,Entire home/apt,2007.0,142,28,30.0,45.0,5/21/2022
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,Moderate,Entire home/apt,2009.0,204,41,10.0,9.0,11/19/2018
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,Flexible,Entire home/apt,2013.0,577,115,3.0,74.0,6/22/2019
7,1005202,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,Moderate,Private room,2009.0,"1,060",212,45.0,49.0,10/5/2017

In [62]:
final_stage_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 83969 entries, 0 to 102040
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      83969 non-null  int64
 1   Name                    83969 non-null  object
 2   Host id                 83969 non-null  int64
 3   Host_identity_verified  83969 non-null  object
 4   Host name               83969 non-null  object
 5   Neighbourhood group     83969 non-null  object
 6   Neighbourhood           83969 non-null  object
 7   Lat                     83969 non-null  float64
 8   Long                    83969 non-null  float64
 9   Country                 83969 non-null  object
 10  Country code            83969 non-null  object
 11  Instant_bookable        83969 non-null  object
 12  Cancellation_policy     83969 non-null  object
 13  Room type               83969 non-null  object
 14  Construction year       83969 non-null  float64
 15  Price                   83969 non-null  object
 16  Service fee             83969 non-null  object
 17  Minimum nights          83969 non-null  float64
 18  Number of reviews       83969 non-null  float64
 19  Last review             83969 non-null  object
dtypes: float64(5), int64(2), object(13)
memory usage: 13.5+ MB

In [63]:
final_stage_data['Price'] = final_stage_data['Price'].str.replace(',','')

In [64]:
final_stage_data['Price'] = pd.to_numeric(final_stage_data['Price'])

In [65]:
final_stage_data['Service fee'] = pd.to_numeric(final_stage_data['Service fee'])

In [66]:
final_stage_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 83969 entries, 0 to 102040
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      83969 non-null  int64
 1   Name                    83969 non-null  object
 2   Host id                 83969 non-null  int64
 3   Host_identity_verified  83969 non-null  object
 4   Host name               83969 non-null  object
 5   Neighbourhood group     83969 non-null  object
 6   Neighbourhood           83969 non-null  object
 7   Lat                     83969 non-null  float64
 8   Long                    83969 non-null  float64
 9   Country                 83969 non-null  object
 10  Country code            83969 non-null  object
 11  Instant_bookable        83969 non-null  object
 12  Cancellation_policy     83969 non-null  object
 13  Room type               83969 non-null  object
 14  Construction year       83969 non-null  float64
 15  Price                   83969 non-null  int64
 16  Service fee             83969 non-null  int64
 17  Minimum nights          83969 non-null  float64
 18  Number of reviews       83969 non-null  float64
 19  Last review             83969 non-null  object
dtypes: float64(5), int64(4), object(11)
memory usage: 13.5+ MB

In [67]:
final_stage_data.head(10)

,Id,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Last review
0,1001254,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,Strict,Private room,2020.0,966,193,10.0,9.0,10/19/2021
1,1002102,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,Moderate,Entire home/apt,2007.0,142,28,30.0,45.0,5/21/2022
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,Moderate,Entire home/apt,2009.0,204,41,10.0,9.0,11/19/2018
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,Flexible,Entire home/apt,2013.0,577,115,3.0,74.0,6/22/2019
7,1005202,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,Moderate,Private room,2009.0,1060,212,45.0,49.0,10/5/2017
8,1005754,Large Furnished Room Near B'way,79384379533,Verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,US,True,Strict,Private room,2005.0,1018,204,2.0,430.0,6/24/2019
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,Unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,US,False,Strict,Private room,2015.0,291,58,2.0,118.0,7/21/2017
10,1006859,Cute & Cozy Lower East Side 1 bdrm,1280143094,Verified,Miranda,Manhattan,Chinatown,40.71344,-73.99037,United States,US,False,Flexible,Entire home/apt,2004.0,319,64,1.0,160.0,6/9/2019
11,1007411,Beautiful 1br on Upper West Side,18824631834,Verified,Alan,Manhattan,Upper West Side,40.80316,-73.96545,United States,US,True,Flexible,Entire home/apt,2008.0,606,121,5.0,53.0,6/22/2019
13,1008516,"Lovely Room 1, Garden, Best Area, Legal rental",26802410424,Verified,Darcy,brookln,South Slope,40.66829,-73.98779,United States,US,True,Moderate,Private room,2010.0,580,116,4.0,167.0,6/24/2019

In [68]:
final_stage_data['Construction year'] = final_stage_data['Construction year'].astype(int)

Year Should not be float.

In [69]:
final_stage_data.head()

,Id,Name,Host id,Host_identity_verified,Host name,Neighbourhood group,Neighbourhood,Lat,Long,Country,Country code,Instant_bookable,Cancellation_policy,Room type,Construction year,Price,Service fee,Minimum nights,Number of reviews,Last review
0,1001254,Clean & quiet apt home by the park,80014485718,Unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,Strict,Private room,2020,966,193,10.0,9.0,10/19/2021
1,1002102,Skylit Midtown Castle,52335172823,Verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,Moderate,Entire home/apt,2007,142,28,30.0,45.0,5/21/2022
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,Verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,Moderate,Entire home/apt,2009,204,41,10.0,9.0,11/19/2018
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,Verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,US,True,Flexible,Entire home/apt,2013,577,115,3.0,74.0,6/22/2019
7,1005202,BlissArtsSpace!,90821839709,Unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,US,False,Moderate,Private room,2009,1060,212,45.0,49.0,10/5/2017

In [70]:
final_stage_data.to_csv(r'D:\My Statistics\Data Cleaning With Python\Airnb Data Cleaning With Python\airnb_clean_data.csv',index= False)